default:
  ssh-path: internal
  local-editor:
    - nvim-qt
    - --nofork
    - --server
    - "{{SOCKET_PATH}}"
  # local-editor:
  #   - neovide
  #   - --neovim-bin
  #   - /opt/homebrew/bin/nvim
  #   - --server
  #   - "{{SOCKET_PATH}}"
  #   - --no-fork
  #   - --no-multigrid

servers:
  vscode-remote:
    use-nvim-embed: true
    nvim-cmd:
      # - /home/linuxbrew/.linuxbrew/bin/nvim
      - /home/mike/Work/neovim/nvim-dev

  nvrh-test-linux:
    use-nvim-embed: true
    nvim-cmd:
      # - /home/linuxbrew/.linuxbrew/bin/nvim
      - /home/mike/Work/neovim/nvim-dev

  vscode-remote-via-maury:
    ssh-path: binary
    nvim-cmd:
      - /home/linuxbrew/.linuxbrew/bin/nvim

  nvrh-test-windows:
    nvim-cmd:
      - mise
      - exec
      - --
      - nvim
