#!/usr/bin/env bash
set -ex

cd "$(dirname "$0")"

find . -maxdepth 1 -type d -not -name '.' -not -name '.git' -not -name 'examples' | while read -r line; do
  # Remove the leading './' from the directory name
  PACKAGE_NAME="${line#./}"
  stow -vt ~ "$PACKAGE_NAME"
done
